CMS:
  PyroCMS:
    version_page: https://codeigniter.pyrocms.com/store/details/pyrocms_professional
    regexp: /version/
  ModX:
    version_page: https://codeigniter.pyrocms.com/store/details/pyrocms_professional
    regexp: /version/
  